// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDK4CXCDoCyIKECpiSrxOCR-U1XA2q13MA',
    appId: '1:743211273882:web:84fe78e9d0849616cb5923',
    messagingSenderId: '743211273882',
    projectId: 'ecommerceapp-9dac8',
    authDomain: 'ecommerceapp-9dac8.firebaseapp.com',
    storageBucket: 'ecommerceapp-9dac8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBS5a4fXBV9T3IVBN8PKFkptmg8ELDuikU',
    appId: '1:743211273882:android:831a6632e87cd71dcb5923',
    messagingSenderId: '743211273882',
    projectId: 'ecommerceapp-9dac8',
    storageBucket: 'ecommerceapp-9dac8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1YJoCsk1sCrhcztcwMtnb1AkuEqHw0rc',
    appId: '1:743211273882:ios:55c368e2fee745eacb5923',
    messagingSenderId: '743211273882',
    projectId: 'ecommerceapp-9dac8',
    storageBucket: 'ecommerceapp-9dac8.appspot.com',
    androidClientId: '743211273882-ofbt9hjo4q7nquela05c6254uegkckum.apps.googleusercontent.com',
    iosClientId: '743211273882-4rqqbbnmotihmr59v6oa48i4escl9vfk.apps.googleusercontent.com',
    iosBundleId: 'com.example.tStore',
  );
}
